spring:
  datasource:
    url: jdbc:mysql://121.196.47.181:3306/NursingHomeSystem?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowMultiQueries=true
    username: root
    password: test@#678root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 100
    maxActive: 500
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 100
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000



mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  address: 0.0.0.0
  port: 80

debug: true